/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphtheory;
//final
import Algorithm.Edge;
import Algorithm.Vertex;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author lanfouf
 */
public class FrameRes extends javax.swing.JFrame {

    
    PanRes panD;
    private List<Vertex> v;
    private List<Edge> e;
    private Boolean bool;
    private String str;
    private int Acm ;
 
    public FrameRes(List<Vertex> v,List<Edge> e,Boolean bool) {
        initComponents();
        panD=new PanRes(v,e,bool);
        setLayout(new BorderLayout());
        this.v=v;
        this.e=e;
        this.bool=bool;
        panD=new PanRes(v,e,bool);
        
        
        this.add(jPanel1,BorderLayout.NORTH);
        this.add(panD,BorderLayout.CENTER);
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        Restext.setVisible(false);
        algo.setVisible(false);
        
    }
    public FrameRes(List<Vertex> v,List<Edge> e,Boolean bool,String txt,List<Integer> res) {
        initComponents();
        this.algo.setText(txt);
        panD=new PanRes(v,e,bool);
        setLayout(new BorderLayout());
        this.v=v;
        this.e=e;
        this.bool=bool;
        panD=new PanRes(v,e,bool);
        
        
        this.add(jPanel1,BorderLayout.NORTH);
        this.add(panD,BorderLayout.CENTER);
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        Restext.setLineWrap(true);
        Restext.setWrapStyleWord(true);
        Restext.setEditable(false);
        
        for (int i = 0; i < res.size(); i++) {
            Restext.append(res.get(i)+"-->");
            
        }
        
    }
    public FrameRes(List<Vertex> v,List<Edge> e,Boolean bool,String txt,int res) {
        initComponents();
        this.algo.setText(txt);
        panD=new PanRes(v,e,bool);
        setLayout(new BorderLayout());
        this.v=v;
        this.e=e;
        this.bool=bool;
        panD=new PanRes(v,e,bool);
        
        
        this.add(jPanel1,BorderLayout.NORTH);
        this.add(panD,BorderLayout.CENTER);
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        Restext.setLineWrap(true);
        Restext.setWrapStyleWord(true);
        Restext.setEditable(false);
        
        Restext.setText(res+"");
        
    }

    FrameRes() {
        initComponents();
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Restext = new javax.swing.JTextArea();
        algo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Restext.setColumns(20);
        Restext.setRows(5);
        jScrollPane1.setViewportView(Restext);

        algo.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(algo)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(algo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 500, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrameRes f=new FrameRes();
                f.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Restext;
    private javax.swing.JLabel algo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
